name: Test
on:
  workflow_dispatch:
    inputs:
      temp_value:
        description: 'dummy'
        type: string
        required: false
        default: "A"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "Input = ${{ inputs.temp_value }}"
